local source = debug.getinfo(1, "S").source
local theme_file = source:sub(1, 1) == "@" and source:sub(2) or source
local root = vim.fn.fnamemodify(theme_file, ":h:h")
local c = dofile(root .. "/colors.lua")

vim.cmd("highlight clear")

if vim.fn.exists("syntax_on") == 1 then
	vim.cmd("syntax reset")
end

vim.o.termguicolors = true
vim.g.colors_name = "forest"

local function hl(group, spec)
	vim.api.nvim_set_hl(0, group, spec)
end

local none = "NONE"

-- Core editor UI
hl("Normal", { fg = c.fg, bg = c.bg })
hl("NormalNC", { fg = c.fg_dark, bg = c.bg })
hl("NormalFloat", { fg = c.fg, bg = c.bg_light })
hl("FloatBorder", { fg = c.forest_2, bg = c.bg_light })
hl("FloatTitle", { fg = c.lichen, bg = c.bg_light, bold = true })
hl("ColorColumn", { bg = c.bg_light })
hl("Conceal", { fg = c.mist })
hl("Cursor", { fg = c.bg, bg = c.lichen })
hl("CursorIM", { fg = c.bg, bg = c.lichen })
hl("CursorColumn", { bg = c.bg_light })
hl("CursorLine", { bg = c.bg_light })
hl("CursorLineNr", { fg = c.lichen, bg = c.bg_light, bold = true })
hl("LineNr", { fg = c.comment })
hl("SignColumn", { fg = c.comment, bg = c.bg })
hl("Folded", { fg = c.sage, bg = c.bg_light })
hl("FoldColumn", { fg = c.comment, bg = c.bg })
hl("VertSplit", { fg = c.forest_0 })
hl("WinSeparator", { fg = c.forest_0 })
hl("StatusLine", { fg = c.fg, bg = c.forest_0 })
hl("StatusLineNC", { fg = c.fg_dark, bg = c.bg_light })
hl("TabLine", { fg = c.fg_dark, bg = c.bg_light })
hl("TabLineFill", { bg = c.bg_dark })
hl("TabLineSel", { fg = c.bg, bg = c.accent, bold = true })
hl("Pmenu", { fg = c.fg, bg = c.bg_light })
hl("PmenuSel", { fg = c.bg, bg = c.creek })
hl("PmenuSbar", { bg = c.forest_0 })
hl("PmenuThumb", { bg = c.forest_2 })
hl("WildMenu", { fg = c.bg, bg = c.lichen })
hl("Visual", { bg = c.forest_0 })
hl("VisualNOS", { bg = c.forest_0 })
hl("Search", { fg = c.bg_dark, bg = c.amber })
hl("IncSearch", { fg = c.bg_dark, bg = c.lichen, bold = true })
hl("CurSearch", { fg = c.bg_dark, bg = c.lichen, bold = true })
hl("Substitute", { fg = c.bg_dark, bg = c.berry })
hl("MatchParen", { fg = c.lichen, bg = c.forest_0, bold = true })
hl("NonText", { fg = c.forest_0 })
hl("Whitespace", { fg = c.forest_0 })
hl("SpecialKey", { fg = c.forest_1 })
hl("Directory", { fg = c.creek })
hl("Title", { fg = c.lichen, bold = true })
hl("Question", { fg = c.lichen })
hl("MoreMsg", { fg = c.fern })
hl("ModeMsg", { fg = c.sage })
hl("WarningMsg", { fg = c.amber })
hl("ErrorMsg", { fg = c.red, bold = true })
hl("MsgArea", { fg = c.fg })
hl("MsgSeparator", { fg = c.forest_0 })
hl("QuickFixLine", { bg = c.forest_0, bold = true })
hl("Underlined", { fg = c.mist, underline = true })
hl("Ignore", { fg = c.comment })
hl("Error", { fg = c.red, bg = none, bold = true })
hl("Todo", { fg = c.bg_dark, bg = c.amber, bold = true })

-- Base syntax
hl("Comment", { fg = c.comment, italic = true })
hl("Constant", { fg = c.berry })
hl("String", { fg = c.bark_2 })
hl("Character", { fg = c.bark_2 })
hl("Number", { fg = c.berry })
hl("Boolean", { fg = c.berry })
hl("Float", { fg = c.berry })
hl("Identifier", { fg = c.fg })
hl("Function", { fg = c.bark_2 })
hl("Statement", { fg = c.fern })
hl("Conditional", { fg = c.fern })
hl("Repeat", { fg = c.fern })
hl("Label", { fg = c.fern })
hl("Operator", { fg = c.mist })
hl("Keyword", { fg = c.fern })
hl("Exception", { fg = c.red })
hl("PreProc", { fg = c.bark_light })
hl("Include", { fg = c.mist })
hl("Define", { fg = c.bark_light })
hl("Macro", { fg = c.bark_light })
hl("PreCondit", { fg = c.bark_light })
hl("Type", { fg = c.bark_2 })
hl("StorageClass", { fg = c.fern })
hl("Structure", { fg = c.creek })
hl("Typedef", { fg = c.creek })
hl("Special", { fg = c.amber })
hl("SpecialChar", { fg = c.amber })
hl("Tag", { fg = c.creek })
hl("Delimiter", { fg = c.fg_dark })
hl("SpecialComment", { fg = c.sage, italic = true })
hl("Debug", { fg = c.red })

-- Diagnostics and LSP
hl("DiagnosticError", { fg = c.red })
hl("DiagnosticWarn", { fg = c.amber })
hl("DiagnosticInfo", { fg = c.mist })
hl("DiagnosticHint", { fg = c.sage })
hl("DiagnosticOk", { fg = c.lichen })
hl("DiagnosticUnderlineError", { sp = c.red, undercurl = true })
hl("DiagnosticUnderlineWarn", { sp = c.amber, undercurl = true })
hl("DiagnosticUnderlineInfo", { sp = c.mist, undercurl = true })
hl("DiagnosticUnderlineHint", { sp = c.sage, undercurl = true })
hl("DiagnosticVirtualTextError", { fg = c.red, bg = c.bg_light })
hl("DiagnosticVirtualTextWarn", { fg = c.amber, bg = c.bg_light })
hl("DiagnosticVirtualTextInfo", { fg = c.mist, bg = c.bg_light })
hl("DiagnosticVirtualTextHint", { fg = c.sage, bg = c.bg_light })
hl("LspReferenceText", { bg = c.forest_0 })
hl("LspReferenceRead", { bg = c.forest_0 })
hl("LspReferenceWrite", { bg = c.forest_0 })
hl("LspSignatureActiveParameter", { fg = c.bg, bg = c.lichen, bold = true })

-- Diffs and git signs
hl("DiffAdd", { fg = c.lichen, bg = c.forest_0 })
hl("DiffChange", { fg = c.amber, bg = c.bg_light })
hl("DiffDelete", { fg = c.red, bg = c.bg_light })
hl("DiffText", { fg = c.bg_dark, bg = c.amber })
hl("Added", { fg = c.lichen })
hl("Changed", { fg = c.amber })
hl("Removed", { fg = c.red })
hl("GitSignsAdd", { fg = c.lichen })
hl("GitSignsChange", { fg = c.amber })
hl("GitSignsDelete", { fg = c.red })

-- Tree-sitter captures
hl("@comment", { link = "Comment" })
hl("@constant", { link = "Constant" })
hl("@constant.builtin", { fg = c.amber, bold = true })
hl("@string", { link = "String" })
hl("@string.escape", { fg = c.amber })
hl("@number", { link = "Number" })
hl("@boolean", { link = "Boolean" })
hl("@function", { fg = c.bark_2 })
hl("@function.builtin", { fg = c.berry })
hl("@function.call", { fg = c.berry })
hl("@constructor", { fg = c.creek })
hl("@variable", { fg = c.fg })
hl("@variable.builtin", { fg = c.amber, italic = true })
hl("@parameter", { fg = c.fg })
hl("@property", { fg = c.sage })
hl("@field", { fg = c.sage })
hl("@keyword", { link = "Keyword" })
hl("@keyword.function", { fg = c.fern })
hl("@keyword.operator", { fg = c.berry })
hl("@operator", { link = "Operator" })
hl("@type", { link = "Type" })
hl("@type.builtin", { fg = c.creek, bold = true })
hl("@tag", { fg = c.creek })
hl("@tag.attribute", { fg = c.sage })
hl("@tag.delimiter", { fg = c.fg_dark })
hl("@punctuation.delimiter", { fg = c.fg_dark })
hl("@punctuation.bracket", { fg = c.fg_dark })
hl("@punctuation.special", { fg = c.amber })

-- Telescope
hl("TelescopeNormal", { fg = c.fg, bg = c.bg })
hl("TelescopeBorder", { fg = c.forest_1, bg = c.bg })
hl("TelescopePromptNormal", { fg = c.fg, bg = c.bg_light })
hl("TelescopePromptBorder", { fg = c.forest_2, bg = c.bg_light })
hl("TelescopePromptTitle", { fg = c.bg, bg = c.lichen, bold = true })
hl("TelescopePreviewTitle", { fg = c.bg, bg = c.creek, bold = true })
hl("TelescopeResultsTitle", { fg = c.bg, bg = c.amber, bold = true })
hl("TelescopeSelection", { fg = c.fg, bg = c.forest_0 })
hl("TelescopeMatching", { fg = c.lichen, bold = true })

-- nvim-cmp
hl("CmpItemAbbr", { fg = c.fg })
hl("CmpItemAbbrDeprecated", { fg = c.comment, strikethrough = true })
hl("CmpItemAbbrMatch", { fg = c.lichen, bold = true })
hl("CmpItemAbbrMatchFuzzy", { fg = c.lichen })
hl("CmpItemKind", { fg = c.mist })
hl("CmpItemMenu", { fg = c.comment })

-- Statusline-friendly groups
hl("ForestStatusNormal", { fg = c.bg, bg = c.lichen, bold = true })
hl("ForestStatusInsert", { fg = c.bg, bg = c.creek, bold = true })
hl("ForestStatusVisual", { fg = c.bg, bg = c.amber, bold = true })
hl("ForestStatusReplace", { fg = c.bg, bg = c.berry, bold = true })
hl("ForestStatusCommand", { fg = c.bg, bg = c.moss, bold = true })
